export const weatherConditions = [
  {
    id: 1,
    condition: "Thunderstorm",
    joke: "Thunderstorms are nature's drum solo.",
    color: "bg-lime-200",
    image: "./assets/thunderstorm.png",
  },
  {
    id: 2,
    condition: "Drizzle",
    joke: "Drizzle is like nature's way of saying, 'I'm not in a rush.'",
    color: "bg-teal-200",
    image: "",
  },
  {
    id: 3,
    condition: "Rain",
    joke: "Rainy days are just nature's way of helping us appreciate the sunshine.",
    color: "bg-blue-200",
    image: "./assets/rain.png",
  },
  {
    id: 4,
    condition: "Snow",
    joke: "Snowflakes are like nature's confetti in winter.",
    color: "bg-gray-100",
    image: "",
  },
  {
    id: 5,
    condition: "Mist",
    joke: "Mist makes everything look a bit more mysterious.",
    color: "bg-green-200",
    image: "",
  },
  {
    id: 6,
    condition: "Smoke",
    joke: "Smoke signals from nature: time for a BBQ.",
    color: "bg-gray-300",
    image: "",
  },
  {
    id: 7,
    condition: "Haze",
    joke: "Haze is like nature's way of adding a soft filter to the world.",
    color: "bg-orange-200",
    image: "",
  },
  {
    id: 8,
    condition: "Dust",
    joke: "Dust storms: nature's way of giving us a surprise exfoliation.",
    color: "bg-yellow-200",
    image: "",
  },
  {
    id: 9,
    condition: "Fog",
    joke: "Fog is like nature's way of making the world feel a bit more cozy.",
    color: "bg-indigo-200",
    image: "",
  },
  {
    id: 10,
    condition: "Sand",
    joke: "Sandstorms: when nature decides it's time for a desert dance party.",
    color: "bg-yellow-200",
    image: "",
  },
  {
    id: 11,
    condition: "Ash",
    joke: "Volcanic ash: nature's way of reminding us who's boss.",
    color: "bg-red-200",
    image: "",
  },
  {
    id: 12,
    condition: "Squall",
    joke: "Squalls are like nature's gusty hugs.",
    color: "bg-green-200",
    image: "",
  },
  {
    id: 13,
    condition: "Tornado",
    joke: "Tornadoes: when nature decides to spin things up a bit.",
    color: "bg-red-200",
    image: "",
  },
  {
    id: 14,
    condition: "Clear",
    joke: "Clear skies: nature's way of telling us it's a good day to go outside.",
    color: "bg-purple-200",
    image: "./assets/clear.png",
  },
  {
    id: 15,
    condition: "Clouds",
    joke: "Clouds are like nature's ever-changing art in the sky.",
    color: "bg-rose-200",
    image: "./assets/clouds.png",
  },
];
